-- Verbatim B42.20 kitchen pool definitions, extracted from
-- media/lua/server/Items/ProceduralDistributions.lua (Aug 2026 upload).
-- Ground truth for offline solver checks and nContainers tuning (ticket 4).
-- NOTE: KitchenMicrowave carries pool flags cookFood and onlyOne.

	KitchenBaking = {
		ignoreZombieDensity = true,
		rolls = 4,
		items = {
			-- Ingredients
			"BakingSoda", 1,
			"CannedMilk", 1,
			"Chocolate", 2,
			"ChocolateChips", 1,
			"Cinnamon", 1,
			"CocoaPowder", 1,
			"Cornflour2", 0.5,
			"Cornmeal2", 0.5,
			"Flour2", 4,
			"GrahamCrackers", 1,
			"GravyMix", 0.5,
			"Marshmallows", 1,
			"OilOlive", 1,
			"OilVegetable", 1,
			"PancakeMix", 2,
			"Sugar", 2,
			"SugarBrown", 2,
			"SugarCubes", 6,
			"Vinegar2", 1,
			"Vinegar_Jug", 0.05,
			"Yeast", 4,
			-- Trays/Dishes
			"BakingPan", 4,
			"BakingTray", 4,
			"Bowl", 8,
			"MuffinTray", 4,
			-- Utensils
			"Ladle", 6,
			"RollingPin", 4,
			"Spoon", 10,
			"Whisk", 8,
			-- Misc.
			"Aluminum", 2,
			"DishCloth", 10,
			"OvenMitt", 8,
			"Sparklers", 0.5,
		},
		junk = {
			rolls = 1,
			items = {
				"DeadMouse", 1,
				"DeadRat", 1,
				"Yeast", 4,

			}
		}
	},

	KitchenBook = {
		rolls = 4,
		items = {
			-- Skill Books
			"BookButchering1", 2,
			"BookButchering2", 1,
			"BookButchering3", 0.5,
			"BookCooking1", 2,
			"BookCooking2", 1,
			"BookCooking3", 0.5,
			"BookFarming1", 2,
			"BookFarming2", 1,
			"BookFarming3", 0.5,
			"BookFirstAid1", 2,
			"BookHusbandry1", 2,
			"BookHusbandry2", 1,
			"BookHusbandry3", 0.5,
			"BookTailoring1", 2,
			"BookTailoring2", 1,
			"BookTailoring3", 0.5,
			-- Literature (Recipes)
			"CookingMag1", 0.1,
			"CookingMag2", 0.1,
			"CookingMag3", 0.1,
			"CookingMag4", 0.1,
			"CookingMag5", 0.1,
			"CookingMag6", 0.1,
			"FarmingMag1", 0.1,
			"FarmingMag2", 0.1,
			"FarmingMag3", 0.1,
			"FarmingMag4", 0.1,
			"FarmingMag5", 0.1,
			"FarmingMag6", 0.1,
			"FarmingMag7", 0.1,
			"FarmingMag8", 0.1,
			"KnittingMag1", 0.5,
			"KnittingMag2", 0.5,
			"RecipeClipping", 10,
            "TailoringMag1", 0.1,
            "TailoringMag2", 0.5,
            "TailoringMag3", 0.1,
            "TailoringMag4", 0.5,
            "TailoringMag5", 0.5,
            "TailoringMag6", 0.1,
            "TailoringMag7", 0.5,
            "TailoringMag8", 0.5,
            "TailoringMag9", 0.5,
            "TailoringMag10", 0.1,
			-- Stationery
			"BluePen", 4,
			"Calculator", 0.5,
			"Eraser", 4,
			"Glue", 1,
			"GreenPen", 1,
			"MarkerBlack", 1,
			"MarkerBlue", 0.1,
			"MarkerGreen", 0.1,
			"MarkerRed", 0.1,
			"Paperclip", 8,
			"PaperclipBox", 0.1,
			"Pen", 4,
			"Pencil", 8,
			"RedPen", 4,
			"RubberBand", 6,
			"Scissors", 2,
			"ScissorsBlunt", 2,
			"Scotchtape", 4,
			-- Literature (Generic)
			"Brochure", 8,
			"Catalog", 10,
			"DoodleKids", 10,
			"Flier", 8,
			"GenericMail", 20,
			"IndexCard", 20,
			"LetterHandwritten", 10,
			"Magazine", 6,
			"Magazine_Popular", 10,
			"Newspaper", 4,
			"Newspaper_Recent", 4,
			"Note", 20,
			"Notebook", 4,
			"Notepad", 8,
			"Paperback", 4,
			"Paperback_Diet", 4,
			"Paperback_Medical", 4,
			"Phonebook", 20,
			"Photo", 10,
			"Receipt", 20,
			"TVMagazine", 6,
			-- Electronics
			"CordlessPhone", 4,
			"RadioBlack", 2,
			"RadioRed", 1,
		},
		junk = {
			rolls = 1,
			items = {
				"BobPic", 0.001,
				"CaseyPic", 0.001,
				"ChrisPic", 0.001,
				"CortmanPic", 0.001,
				"HankPic", 0.001,
				"JamesPic", 0.001,
				"KatePic", 0.001,
				"MariannePic", 0.001,
				"IDcard", 1,
			}
		}
	},

	KitchenBottles = {
		ignoreZombieDensity = true,
		rolls = 2, -- reduced to 2 from 4 to rebalance food spawns
		items = {
			"BeerBottle", 1,
			"BeerCan", 2,
			"BeerCanPack", 0.01,
			"BeerPack", 0.01,
			"Flask", 0.1,
			"JuiceBox", 4,
			"JuiceBoxApple", 4,
			"JuiceBoxFruitpunch", 4,
			"JuiceBoxOrange", 4,
			"Pop", 8,
			"Pop2", 8,
			"Pop3", 8,
			"PopBottle", 4,
			"PopBottleRare", 0.1,
			"SodaCan", 8,
			--"SodaCanRare", 2,
			"WaterBottle", 4,
			"Whiskey", 2,
			"Wine", 1,
			"Wine2", 1,
			"WineBox", 2,
		},
		junk = {
			rolls = 4,
			items = {
				"BottleOpener", 10,
				"Corkscrew", 4,
				"DishCloth", 10,
				"DrinkingGlass", 10,
				"GlassTumbler", 8,
				"GlassWine", 4,
				"PlasticCup", 10,
			}
		}
	},

	KitchenBreakfast = {
		ignoreZombieDensity = true,
		rolls = 2, -- reduced to 2 from 4 to rebalance food spawns
		items = {
			"Bread", 6,
			"CannedMilk", 2,
			"Cereal", 8,
			"Chocolate", 6,
			"Cinnamon", 4,
			"Coffee2", 4,
			"CookieJar", 0.1,
			"CookieJar_Bear", 0.001,
			"Crackers", 8,
			"GranolaBar", 6,
			"Honey", 4,
			"JamFruit", 6,
			"JamMarmalade", 1,
			"MapleSyrup", 4,
			"OatsRaw", 6,
			"PancakeMix", 6,
			"PeanutButter", 8,
			"Sugar", 2,
			"SugarBrown", 2,
			"SugarCubes", 6,
			"Teabag2", 4,
		},
		junk = {
			rolls = 1,
			items = {
				"DeadMouse", 1,
				"DeadRat", 1,
				"DishCloth", 10,
			}
		}
	},

	KitchenCannedFood = {
		ignoreZombieDensity = true,
		rolls = 2,
		items = {
			"CannedBolognese", 4,
			"CannedCarrots2", 2,
			"CannedChili", 4,
			"CannedCorn", 2,
			"CannedCornedBeef", 4,
			"CannedFruitBeverage", 4,
			"CannedFruitCocktail", 4,
			"CannedMilk", 1,
			"CannedMushroomSoup", 4,
			"CannedPeaches", 2,
			"CannedPeas", 2,
			"CannedPineapple", 2,
			"CannedPotato2", 2,
			"CannedSardines", 4,
			"CannedTomato2", 2,
			"Dogfood", 1,
			"MysteryCan", 1,
			"TinnedBeans", 4,
			"TinnedSoup", 4,
			"TinOpener", 8,
			"TinOpener_Old", 2,
			"TomatoPaste", 2,
			"TunaTin", 2,
			"Vinegar2", 1,
			"Vinegar_Jug", 0.05,
		},
		junk = {
			rolls = 1,
			items = {
				"DeadMouse", 1,
				"DeadRat", 1,
				"DentedCan", 2,
				"DishCloth", 10,
				"MysteryCan", 1,
			}
		}
	},

	KitchenDishes = {
		rolls = 4,
		items = {
			"Bowl", 10,
			"BreadKnife", 8,
			"ButterKnife", 10,
			"CarvingFork2", 4,
			"CheeseGrater", 8,
			"DrinkingGlass", 10,
			"Fleshing_Tool", 0.01,
			"Fork", 10,
			"GlassTumbler", 8,
			"GlassWine", 4,
			"KitchenKnife", 6,
			"KnifeFillet", 6,
			"KnifeParing", 6,
			"KitchenTongs", 8,
			"Ladle", 8,
			"LargeKnife", 0.1,
			"MeatCleaver", 4,
			"MortarPestle", 0.5,
			"Mugl", 10,
			"PizzaCutter", 6,
			"Plate", 10,
			"Spatula", 8,
			"Spoon", 10,
			"Strainer", 8,
			"Teacup", 4,
			"TinOpener", 8,
			"TinOpener_Old", 2,
			"Whetstone", 4,
			"Whisk", 8,
		},
		junk = {
			rolls = 1,
			items = {
				"DishCloth", 10,
			}
		}
	},

	KitchenDryFood = {
		ignoreZombieDensity = true,
		rolls = 2, -- reduced to 2 from 4 to rebalance food spawns
		items = {
			"BouillonCube", 10,
			"Cereal", 8,
			"Chocolate", 6,
			"Crackers", 8,
			"Crisps", 4,
			"Crisps2", 4,
			"Crisps3", 4,
			"Crisps4", 4,
			"DriedApricots", 6,
			"DriedBlackBeans", 2, -- halved their value to rebalance food
			"DriedChickpeas", 2, -- halved their value to rebalance food
			"DriedKidneyBeans", 2, -- halved their value to rebalance food
			"DriedLentils", 2, -- halved their value to rebalance food
			"DriedSplitPeas", 2, -- halved their value to rebalance food
			"DriedWhiteBeans", 2, -- halved their value to rebalance food
			"Macandcheese", 8,
			"Macaroni", 2,
			"Marinara", 8,
			"Pasta", 2,
			"Pepper", 20,
			"Popcorn", 6,
			"PorkRinds", 4,
			"Ramen", 4,
			"Rice", 2,
			"Salt", 20,
			"PowderedGarlic", 4,
			"PowderedOnion", 4,
			"SeasoningSalt", 6,
			"TacoShell", 2,
			"Tortilla", 2,
			"TortillaChips", 4,
			"Vinegar2", 4,
			"Vinegar_Jug", 0.2,
			"Yeast", 10,
		},
		junk = {
			rolls = 1,
			items = {
				"DeadMouse", 1,
				"DeadRat", 1,
				"DishCloth", 10,
			}
		}
	},

    KitchenMicrowave = {
        ignoreZombieDensity = true,
        rolls = 4,
        cookFood = true,
        onlyOne = true,
        items = {
            "Bacon", 8,
            "Oatmeal", 8,
            "TVDinner", 8,
        },
        junk = {
            rolls = 1,
            cookFood = true,
            items = {

            }
        }
    },

	KitchenPots = {
		rolls = 4,
		items = {
			"BakingPan", 8,
			"BakingTray", 10,
			"BastingBrush", 10,
			"CheeseGrater", 8,
			"CuttingBoardPlastic", 4,
			"CuttingBoardWooden", 4,
			"GridlePan", 8,
			"GrillBrush", 4,
			"Kettle", 10,
			"Kettle_Copper", 1,
			"KitchenTongs", 8,
			"Ladle", 8,
			"MortarPestle", 0.5,
			"MuffinTray", 8,
			"OvenMitt", 8,
			"Pan", 10,
			"PizzaCutter", 6,
			"Pot", 8,
			"RoastingPan", 8,
			"RollingPin", 8,
			"Saucepan", 10,
			"SaucepanCopper", 2,
			"Spatula", 8,
			"Strainer", 8,
			"TinOpener", 8,
			"Whisk", 8,
		},
		junk = {
			rolls = 1,
			items = {
				"DishCloth", 10,
			}
		}
	},

	KitchenRandom = {
		rolls = 2,
		items = {
			-- Keys/Keyrings
			"CarKey", 2,
			"KeyRing_Bass", 0.001,
			"KeyRing_BlueFox", 0.001,
			"KeyRing_Bug", 0.001,
			"KeyRing_Clover", 0.001,
			"KeyRing_EagleFlag", 0.001,
			"KeyRing_EightBall", 0.001,
			"KeyRing_Hotdog", 0.001,
			"KeyRing_Kitty", 0.001,
			"KeyRing_Panther", 0.001,
			"KeyRing_PineTree", 0.001,
			"KeyRing_PrayingHands", 0.001,
			"KeyRing_RabbitFoot", 0.01,
			"KeyRing_RainbowStar", 0.001,
			"KeyRing_RubberDuck", 0.001,
			"KeyRing_Sexy", 0.001,
			"KeyRing_StinkyFace", 0.001,
			"KeyRing", 1,
			"Key1", 2,
			"Key1", 2,
			"Key1", 2,
			-- Kitchen/Cutlery
			"BottleOpener", 4,
			"CheeseCloth", 8,
			"Chopsticks", 0.05,
			"Corkscrew", 6,
			-- Tools
			"KnifeButterfly", 1,
			"KnifePocket", 0.1,
			"LargeKnife", 0.1,
			"Fleshing_Tool", 0.01,
			"Funnel", 6,
			"Hammer", 4,
			"Handiknife", 0.1,
			"MeasuringTape", 6,
			"Multitool", 0.001,
			"Pliers", 4,
			"Scissors", 1,
			"ScissorsBlunt", 1,
			"Screwdriver", 6,
			"ViseGrips", 1,
			"Whetstone", 4,
			-- Cleaning/Maintenance
			"Bleach", 2,
			"BookMaintenance1", 2,
			"BookMaintenance2", 1,
			"BookMaintenance3", 0.5,
			"CleaningLiquid2", 2,
			"Gloves_Dish", 8,
			"SewingKit", 1,
            "SewingPattern", 0.1,
			"Sponge", 6,
			-- Literature (Generic)
			"Brochure", 2,
			"BusinessCard", 0.5,
			"Card_Birthday", 0.01,
			"Card_Christmas", 0.01,
			"Card_Easter", 0.01,
			"Card_Halloween", 0.01,
			"Card_Hanukkah", 0.01,
			"Card_LunarYear", 0.01,
			"Card_StPatrick", 0.01,
			"Card_Sympathy", 0.01,
			"Card_Valentine", 0.01,
			"Catalog", 8,
			"Flier", 2,
			"IndexCard", 6,
			"Magazine", 3,
			"Magazine_Popular", 3,
			"MenuCard", 6,
			"Note", 8,
			"Notepad", 4,
			"Paperback_Diet", 4,
			"Paperback_Medical", 4,
			"Phonebook", 4,
			"Photo", 1,
			"Receipt", 8,
			"RecipeClipping", 0.5,
			"ScratchTicket", 0.1,
			"ScratchTicket_Winner", 0.1,
			"TVMagazine", 4,
			-- Stationery/Office
			"BluePen", 4,
			"Calculator", 1,
			"Clipboard", 1,
			"Eraser", 4,
			"GraphPaper", 0.05,
			"GreenPen", 2,
			"MarkerBlack", 1,
			"MarkerBlue", 0.5,
			"MarkerGreen", 0.5,
			"MarkerRed", 0.5,
			"Paperclip", 6,
			"Pen", 4,
			"Pencil", 6,
			"RedPen", 4,
			-- Eyewear
			"Glasses_Aviators", 0.5,
			"Glasses_Reading", 1,
			"Glasses_Sun", 1,
			-- Watches
			"WristWatch_Left_ClassicBlack", 0.1,
			"WristWatch_Left_ClassicBrown", 0.1,
			"WristWatch_Left_DigitalBlack", 0.1,
			"WristWatch_Left_DigitalRed", 0.1,
			-- Canning
			"BoxOfJars", 0.1,
			"EmptyJar", 4,
			"JarLid", 4,
			"Vinegar2", 4,
			"Vinegar_Jug", 0.2,
			-- Electronics
			"Battery", 8,
			"BatteryBox", 0.1,
			"HandTorch", 4,
			"HomeAlarm", 0.5,
			"LightBulb", 0.5,
			"LightBulbBlue", 0.01,
			"LightBulbCyan", 0.03,
			"LightBulbGreen", 0.01,
			"LightBulbMagenta", 0.01,
			"LightBulbOrange", 0.006,
			"LightBulbPink", 0.001,
			"LightBulbPurple", 0.003,
			"LightBulbRed", 0.01,
			"LightBulbYellow", 0.06,
			"PowerBar", 4,
			"RadioBlack", 1,
			"RadioRed", 0.5,
			"Timer", 8,
			"Torch", 2,
			-- Firearms

			-- Gardening
			"GardeningSprayEmpty", 2,
			"InsectRepellent", 0.5,
			"SeedBag", 0.5,
			"TrapMouse", 4,
			-- Materials
			"Aluminum", 4,
			"DuctTape", 1,
			"Epoxy", 0.05,
			"Glue", 2,
			"Needle", 2,
			"RubberHose", 0.5,
			"Scotchtape", 4,
			"SteelWool", 6,
			"Thread", 6,
			"Twine", 6,
			"Wire", 2,
			"Woodglue", 0.5,
			"Yarn", 2,
			-- Medical
			"Bandaid", 6,
			"Pills", 0.5,
			"PillsAntiDep", 0.05,
			"PillsBeta", 0.05,
			"PillsVitamins", 0.05,
			-- Pets
			"Dogfood", 2,
			"DogFoodBag", 0.1,
			"DogTag_Pet", 0.5,
			"Leash", 0.5,
			"WaterDishEmpty", 0.5,
			-- Photography
			"Camera", 0.5,
			"CameraDisposable", 0.1,
			"CameraExpensive", 0.001,
			"CameraFilm", 1,
			-- Sports
			"Sportsbottle", 0.1,
			"Whistle", 0.1,
			-- Tobacco/Smoking
			"Cigar", 0.05,
			"CigarettePack", 1,
			"CigaretteRollingPapers", 0.5,
			"Cigarillo", 0.5,
			"LighterBBQ", 2,
			"LighterDisposable", 2,
			"LighterFluid", 0.5,
			"Matchbox", 0.5,
			"Matches", 4,
			"TobaccoChewing", 0.5,
			"TobaccoLoose", 0.5,
			-- Bags
			"Garbagebag", 8,
			"Garbagebag_box", 2,
			"PaperBag", 4,
			"Plasticbag_Bags", 4,
			"Tote_Bags", 2,
			-- Containers
			"CookieJar", 0.05,
			"Cooler", 0.05,
			-- Misc.
			"Buckle", 2,
			"Candle", 6,
			"CardDeck", 4,
			"CombinationPadlock", 0.5,
			"CreditCard", 0.5,
	        "DentalFloss", 0.1,
			"Dice", 4,
			"Doily", 4,
			"HotWaterBottleEmpty", 4,
			-- NOTE: Temporarily bumped for testing purposes.
			"IndustrialDye", 20,
			"Money", 1,
			"Padlock", 0.5,
			"PokerChips", 0.5,
			"Sparklers", 2,
			"Thimble", 4,
			"TissueBox", 1,
			-- Special
			"CookieJar_Bear", 0.001,
			"HollowBook", 0.001,
			"PotScrubberFrog", 0.001,
		},
		junk = {
			rolls = 1,
			items = {
				"BobPic", 0.001,
				"CaseyPic", 0.001,
				"ChrisPic", 0.001,
				"CortmanPic", 0.001,
				"HankPic", 0.001,
				"JamesPic", 0.001,
				"KatePic", 0.001,
				"MariannePic", 0.001,
				"IDcard", 1,
			}
		}
	},
